test: fix flaky router/map_reduce
tarantool/vshard pull request #392
Opened 2023-01-11 10:49 UTC by Serpentian

NO_DOC=bugfix
NO_TEST=<already tested>

2023-01-11 14:43 UTC, Serpentian commented on vshard/util.lua
> +    end
As I said in commit message, errors are inconsistent. Do we want them to be?

Frankly speaking, I don't see it as a big problem, as tnt is a one big inconsistency. If we ever need to deal with timeout error processing, we'll anyway have to use the function, similar to `vtest.error_is_timeout`.

But if we want it, here's the way we may do it:

```diff
diff --git a/vshard/util.lua b/vshard/util.lua
index 45abca2..6e212b2 100644
--- a/vshard/util.lua
+++ b/vshard/util.lua
@@ -293,6 +293,10 @@ local function future_wait(cond, timeout)
     if not err then
         return res
     end
+
+    if err.type == 'TimedOut' then
+        err = lerror.timeout()
+    end
 ::fail::
     return nil, err
 end

```

2023-01-16 17:54 UTC, Serpentian commented on test/unit-luatest/util_test.lua
> +    t.run_only_if(vutil.version_is_at_least(2, 10, 3, nil, 0, 0))
Corresponding commit: https://github.com/tarantool/tarantool/commit/0d944f901cf5400d5832a5528780bb3ecd03ae4b

2023-01-16 21:51 UTC, Gerold103 requested changes
Thanks for the patch! Only some small points, good work.

2023-01-16 21:51 UTC, Gerold103 commented on vshard/util.lua
> +    local res, err = cond:wait_result(timeout)
The comment should be where you do `pcall()`. Here is looks strange that you mention `pcall()` and don't do it.

2023-01-16 21:51 UTC, Gerold103 commented on test/unit-luatest/util_test.lua
> +    conn:wait_connected()
You don't need to wait for connection. `netbox.connect` does it by default.

2023-01-16 21:51 UTC, Gerold103 commented on test/unit-luatest/util_test.lua
> +    f:discard()
You probably shouldn't discard it, if you use it again below.

2023-01-16 21:51 UTC, Gerold103 commented on test/unit-luatest/util_test.lua
> +            return true
In the test case below you send an infinite timeout. Even if you later call `future:discard()`, this fiber will keep hanging in `sleep` until restart. I suggest to add a global flag here like: `while _G.do_sleep do fiber.sleep(0.001) end`. Then in the end you do `_G.do_sleep = false` to unblock the fiber and properly wait for the future to end.

The reason why we shouldn't leave such request-fibers is that they might affect global limits like `box.cfg.net_msg_max`.

2023-01-16 21:51 UTC, Gerold103 commented on vshard/replicaset.lua
> +        res, err = util.future_wait(future, timeout)
Lets add this `local future_wait = util.future_wait` to the beginning of the file (same place where `fiber_cond_wait` is saved) and use this `future_wait()` everywhere. The reason is that in Lua a table index operation like `table.key` is not free, it is computed at runtime on each use.

Same in the router.

2023-01-17 21:49 UTC, Serpentian commented
Everything is fixed

2023-01-19 22:03 UTC, Gerold103 approved these changes
Thanks for the fixes!

2023-01-19 22:03 UTC, merged